networks:
  llm-net:
    external: true

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui_data:/app/backend/data
    environment:
      - "OPENAI_API_BASE_URL=http://llmux:3000/v1"
    ports:
      - "3000:8080"
    networks:
      - llm-net

    # starts when docker starts
    restart: always

volumes:
  open-webui_data: # default settings
