

networks:
  llm-net:
    external: true

services:
  llamacpp:
    build:
      context: .
      dockerfile: ./Dockerfile.rocm-7.2.3
      args:
        - REPO=https://github.com/ggml-org/llama.cpp
        - BRANCH=master
    image: init-js/llamacpp:rocm-7.2.3
    entrypoint: ["/usr/local/bin/llama-server"]

    # to download a model, just pass in
    # docker compose run --rm llamacpp -hf <model>
    command: []
    environment:
      - "HF_TOKEN=${HF_TOKEN:?missing HF_TOKEN}"
      - "LLAMA_ARG_FLASH_ATTN=true"
      # - "LLAMA_ARG_LOAD_MODE=mmap"
      # - "LLAMA_ARG_MMAP=true"
      - "LLAMA_ARG_N_PARALLEL=4"
      - "LLAMA_ARG_HOST=${LLAMA_ARG_HOST:-0.0.0.0}"
      - "LLAMA_ARG_PORT=${LLAMA_ARG_PORT:-8080}"
      # - "LLAMA_ARG_MODELS_PRESET=/presets/models.ini"
      # - "LLAMA_ARG_MODELS_MAX=1"
      # loaded from model
      - "LLAMA_ARG_CTX_SIZE=0"
    volumes:
      - /models/hf-cache:/root/.cache/huggingface
      - ./presets:/presets/:ro
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    ports:
      # host:container
      - "${HOST_BIND_ADDR:-0.0.0.0}:${HOST_BIND_PORT:-8080}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - llm-net
    restart: no


