networks:
  llm_net:
    driver: bridge

services:
  vllm:
    image: vllm/vllm-openai-rocm:latest
    container_name: vllm
    ipc: host
    ports:
      - "8000:8000"
    networks:
      - llm_net
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp=unconfined
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    environment:
      - "HF_TOKEN=${HF_TOKEN}"
    volumes:
      - /scratch/hf-cache:/root/.cache/huggingface
      - ./llvm-config.yaml:/config/llvm-config.yaml
    command: --config /config/llvm-config.yaml
    healthcheck:
      test: ["CMD-SHELL",
             "curl -f --connect-timeout 4 --max-time 9 http://127.0.0.1:8000/health || exit 1"
	    ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 1200s

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui_data:/app/backend/data
    environment:
      - "OPENAI_API_BASE_URL=http://llvm:8000/v1"
    ports:
      - "3000:8080"
    networks:
      - llm_net
    restart: always

volumes:
  open-webui_data: # default settings
